In [1]:
import csv
import pandas as pd
import numpy as np
from collections import defaultdict

In [2]:
df_comp = pd.read_csv("Output Data/Comparison.csv")
M_comp = df_comp.to_numpy()

In [3]:
ID_vec = defaultdict(list)

for ID in M_comp:
    ID_vec[ID[0]].append(ID)

for ID_val in ID_vec:
    ID_vec[ID_val] = np.array(ID_vec[ID_val]) 

ID_list = np.zeros((len(ID_vec),5), dtype=object)

In [11]:
for i, ID in enumerate(ID_vec):
    ID_val = ID_vec[ID]
    track_coverage = np.sum(ID_val[:,15] < 3.5)
    missing_t = ID_val[ID_val[:, 15] > 3.5][:,8]
    ID_list[i][0] = ID_val[0][0]
    ID_list[i][1] = ID_val[0][13]
    ID_list[i][2] = track_coverage
    ID_list[i][3] = missing_t.tolist()
    block_starts = np.where(np.diff(ID_val[:,1]) != 0)[0] + 1
    block_starts = np.insert(block_starts, 0, 0)
    track_index = np.where(np.diff(ID_val[:,1]) != 0)[0] + 1
    track_index = np.insert(track_index, 0, 0)
    Dino_ID = ID_val[:,1][block_starts]
    track_lengths = ID_val[:,14][track_index]
    Dino = np.stack((Dino_ID,block_starts+1,track_lengths), axis=1)
    Dino_all = ';'.join([','.join(map(str, row)) for row in Dino])
    ID_list[i][4] = Dino_all


[14. 15.]
[18. 19. 20.]
[81.]
[]
[88. 89. 90. 92.]
[85. 96.]
[]
[1. 2. 5.]
[ 1.  9. 30. 43.]
[19. 31. 90.]
[81. 83. 84. 85. 86. 87. 88. 89. 90. 91. 92. 94. 96.]
[]
[31. 94. 95. 96. 97. 98. 99.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 13. 14. 95. 96. 97.]
[]
[]
[34. 36. 47. 49. 50. 51. 56. 69. 70. 93. 94. 96. 97. 98. 99.]
[43. 87. 92. 93. 94.]
[82.]
[46. 47. 49.]
[71. 85. 86. 87. 88. 89.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 32. 34. 46. 51. 52. 53.
 54. 55. 56. 57. 62. 64. 65. 66. 67. 68. 69. 70. 71. 72. 73. 74. 75. 76.
 78. 88. 89. 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]
[ 6. 73. 93.]
[1. 4. 6.]
[58. 59. 73. 74. 75. 76. 78. 85. 92. 96. 97. 98.]
[ 3.  4.  5. 57. 89. 98.]
[ 2.  3.  6. 17. 26. 28. 65. 66. 67. 68. 69. 71. 72. 73. 74. 75. 76. 77.
 78. 97.]
[ 5.  6.  7.  8.  9. 38. 42. 43. 44. 45. 46. 48. 59. 60. 61. 62. 63. 64.
 65. 67. 68. 69. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86.
 

In [9]:
df_ID = pd.DataFrame(ID_list, columns = ["ID (CME)","Track Length (CME)","Track Coverage","Missing Time Points","Dino Data"])

In [10]:
df_ID.to_csv("Output Data/ID_Coverage.csv", index = False)